[package]
name = "animations_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.93"
web-sys = { version="0.3.70", features = ["Window", "Document", "HtmlCanvasElement", "CanvasRenderingContext2d"] }

[lib]
crate-type = ["cdylib"]